#!/usr/bin/env bash
set -euo pipefail

ROOT="/Users/qixinchaye/wiki/73神话"
DATE="$(date +%F)"

cd "$ROOT"

/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_shortline_mode_dictionary_scan.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_mode_page_lint.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_mode_page_structure_backfill.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_mode_page_lint.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_trade_mode_attribution_audit.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_trade_mode_attribution_enrich.py" --limit 999 --write --replace
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_mode_alias_normalizer.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_trade_mode_dplus_bridge.py" --write
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_trade_mode_inplace_backfill.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_trade_mode_stats_to_wiki.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_trade_mode_raw_sidecar_backfill.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_trade_mode_environment_split.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_mode_casebook_update.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_user_mode_profile.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_hotlist_effectiveness_validation.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_warroom_mode_feedback.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_source_layering_audit.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_feishu_noise_control.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_git_remote_backup_check.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_autogenerated_artifact_audit.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_trade_mode_bigday_review.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_feishu_protocol_lint.py" --write
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_longrun_execution_dashboard.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_watchdog_self_heal.py"
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_automation_watchdog.py" --write
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_longxia_schedule_watch.py" --date "$DATE" --write
/usr/bin/python3 "$ROOT/raw/07-系统脚本/codex_twelve_task_execution_status.py" --date "$DATE" --write

printf '{"ok":true,"date":"%s","task":"shortline_mode_dictionary_scan"}\n' "$DATE"
